services:

  pg_advertiser:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=rus
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: